import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 这在 Node.js 中运行 - 不要在这里使用客户端代码（浏览器 API、JSX...）

/**
 * 创建侧边栏使你能够：
 - 创建一个有序的文档组
 - 为该组的每个文档呈现一个侧边栏
 - 提供下一个/上一个导航

 侧边栏可以从文件系统生成，也可以在这里显式定义。

 创建尽可能多的侧边栏。
 */
const sidebars: SidebarsConfig = {
  // 默认情况下，Docusaurus 从文档文件夹结构生成侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但你可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
