import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 这在 Node.js 中运行 - 不要在这里使用客户端代码（浏览器 API、JSX...）

/**
 * 创建侧边栏使你能够：
 - 创建一个有序的文档组
 - 为该组的每个文档呈现一个侧边栏
 - 提供下一个/上一个导航

 侧边栏可以从文件系统生成，也可以在这里显式定义。

 创建尽可能多的侧边栏。
 */
const sidebars: SidebarsConfig = {
  // Tutorial 侧边栏 - 自动生成 docs/api 目录下的文档
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],

  // API 侧边栏 - 自动生成 docs/api 目录下的文档
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],

  // apps 侧边栏 - 手动配置 docs/apps 目录下的文档
  appsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'apps',
    },
  ],

  // themes 侧边栏 - 手动配置 docs/themes 目录下的文档
  themesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'themes',
    },
  ],
};

export default sidebars;
